# Generated by Django 4.2.18 on 2025-01-21 14:06

import core.blocks
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="JournalPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "rich_text",
                                wagtail.blocks.RichTextBlock(
                                    features=["bold", "italic", "link", "ol", "ul"],
                                    group="Blocs de texte",
                                    label="Texte riche",
                                ),
                            ),
                            (
                                "engagement",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image"
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                label="Titre", required=False
                                            ),
                                        ),
                                        (
                                            "cta",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "cta_text",
                                                        wagtail.blocks.CharBlock(
                                                            label="Texte du bouton"
                                                        ),
                                                    ),
                                                    (
                                                        "cta_link",
                                                        wagtail.blocks.StreamBlock(
                                                            [
                                                                (
                                                                    "internal",
                                                                    wagtail.blocks.PageChooserBlock(
                                                                        label="Lien interne"
                                                                    ),
                                                                ),
                                                                (
                                                                    "external",
                                                                    wagtail.blocks.URLBlock(
                                                                        label="Lien externe"
                                                                    ),
                                                                ),
                                                                (
                                                                    "email",
                                                                    wagtail.blocks.EmailBlock(
                                                                        label="Email"
                                                                    ),
                                                                ),
                                                            ],
                                                            label="Lien du bouton",
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ],
                                    group="Blocs éditoriaux",
                                    label="Bloc engagement",
                                ),
                            ),
                            (
                                "anchor",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "id",
                                            wagtail.blocks.CharBlock(
                                                help_text="Ce texte sera le texte utilisé pour le lien de l'ancre, et le texte affiché dans l'url au clic sur l'ancre. Il est invisible dans la page. Il peut utiliser tout caractère sauf les espaces, les accents et les majuscules.",
                                                label="Nom de l'ancre",
                                                validators=[
                                                    django.core.validators.RegexValidator(
                                                        re.compile("^[-\\w]+\\Z"),
                                                        "Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.",
                                                        "invalid",
                                                    )
                                                ],
                                            ),
                                        )
                                    ],
                                    group="Blocs éditoriaux",
                                    label="Ancre",
                                ),
                            ),
                            (
                                "quote",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "quote",
                                            wagtail.blocks.TextBlock(
                                                help_text="Les guillemets seront ajoutés automatiquement.",
                                                label="Citation",
                                            ),
                                        ),
                                        (
                                            "author",
                                            wagtail.blocks.CharBlock(
                                                label="Auteur", required=False
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image de profil", required=False
                                            ),
                                        ),
                                    ],
                                    label="Citation",
                                ),
                            ),
                            (
                                "carousel",
                                wagtail.blocks.ListBlock(
                                    core.blocks.ImageBlock,
                                    group="Médias",
                                    icon="image",
                                    label="Carrousel",
                                ),
                            ),
                            (
                                "image",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image"
                                            ),
                                        ),
                                        (
                                            "caption_text",
                                            wagtail.blocks.CharBlock(
                                                label="Légende", required=False
                                            ),
                                        ),
                                        (
                                            "link",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "internal",
                                                        wagtail.blocks.PageChooserBlock(
                                                            label="Lien interne"
                                                        ),
                                                    ),
                                                    (
                                                        "external",
                                                        wagtail.blocks.URLBlock(
                                                            label="Lien externe"
                                                        ),
                                                    ),
                                                    (
                                                        "email",
                                                        wagtail.blocks.EmailBlock(
                                                            label="Email"
                                                        ),
                                                    ),
                                                ],
                                                label="Lien",
                                                required=False,
                                            ),
                                        ),
                                    ],
                                    group="Médias",
                                    label="Image",
                                ),
                            ),
                        ],
                        use_json_field=True,
                        verbose_name="Corps de la page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
