# Generated by Django 4.2.18 on 2025-01-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalpage",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="journalpage",
            name="is_cover_visible",
            field=models.BooleanField(
                default=False,
                help_text="Si la case est cochée, la page de couverture s'affiche, sinon elle sert uniquement de miniature.",
                verbose_name="Apparition de l'image de couverture",
            ),
        ),
        migrations.AddField(
            model_name="journalpage",
            name="season",
            field=models.CharField(
                choices=[
                    ("WIN", "Hiver"),
                    ("SPR", "Printemps"),
                    ("SUM", "Été"),
                    ("AUT", "Automne"),
                ],
                default={},
                help_text="Définit la saison de l'article, cela permet le classement sur la page Journal de Bord.",
                max_length=12,
                verbose_name="Saison",
            ),
            preserve_default=False,
        ),
    ]
