# Generated by Django 4.2.18 on 2025-01-21 15:25

import core.blocks
import django.core.validators
from django.db import migrations
import re
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_journalpage_cover_journalpage_is_cover_visible_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "rich_text",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "hr",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                            ],
                            group="Blocs de texte",
                            label="Texte riche",
                        ),
                    ),
                    (
                        "engagement",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Image"
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        label="Titre", required=False
                                    ),
                                ),
                                (
                                    "cta",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "cta_text",
                                                wagtail.blocks.CharBlock(
                                                    label="Texte du bouton"
                                                ),
                                            ),
                                            (
                                                "cta_link",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "internal",
                                                            wagtail.blocks.PageChooserBlock(
                                                                label="Lien interne"
                                                            ),
                                                        ),
                                                        (
                                                            "external",
                                                            wagtail.blocks.URLBlock(
                                                                label="Lien externe"
                                                            ),
                                                        ),
                                                        (
                                                            "email",
                                                            wagtail.blocks.EmailBlock(
                                                                label="Email"
                                                            ),
                                                        ),
                                                    ],
                                                    label="Lien du bouton",
                                                ),
                                            ),
                                        ],
                                        label="Bouton",
                                    ),
                                ),
                            ],
                            group="Blocs éditoriaux",
                            label="Bloc d'engagement",
                        ),
                    ),
                    (
                        "anchor",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "id",
                                    wagtail.blocks.CharBlock(
                                        help_text="Ce texte sera le texte utilisé pour le lien de l'ancre, et le texte affiché dans l'url au clic sur l'ancre. Il est invisible dans la page. Il peut utiliser tout caractère sauf les espaces, les accents et les majuscules.",
                                        label="Nom de l'ancre",
                                        validators=[
                                            django.core.validators.RegexValidator(
                                                re.compile("^[-\\w]+\\Z"),
                                                "Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.",
                                                "invalid",
                                            )
                                        ],
                                    ),
                                )
                            ],
                            group="Blocs éditoriaux",
                            label="Ancre",
                        ),
                    ),
                    (
                        "quote",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "quote",
                                    wagtail.blocks.TextBlock(
                                        help_text="Les guillemets seront ajoutés automatiquement.",
                                        label="Citation",
                                    ),
                                ),
                                (
                                    "author",
                                    wagtail.blocks.CharBlock(
                                        label="Auteur", required=False
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Image de profil", required=False
                                    ),
                                ),
                            ],
                            group="Blocs éditoriaux",
                            label="Citation",
                        ),
                    ),
                    (
                        "carousel",
                        wagtail.blocks.ListBlock(
                            core.blocks.ImageBlock,
                            group="Médias",
                            icon="image",
                            label="Carousel",
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Image"
                                    ),
                                ),
                                (
                                    "caption_text",
                                    wagtail.blocks.CharBlock(
                                        label="Légende", required=False
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "internal",
                                                wagtail.blocks.PageChooserBlock(
                                                    label="Lien interne"
                                                ),
                                            ),
                                            (
                                                "external",
                                                wagtail.blocks.URLBlock(
                                                    label="Lien externe"
                                                ),
                                            ),
                                            (
                                                "email",
                                                wagtail.blocks.EmailBlock(
                                                    label="Email"
                                                ),
                                            ),
                                        ],
                                        label="Lien",
                                        required=False,
                                    ),
                                ),
                            ],
                            group="Médias",
                            label="Image",
                        ),
                    ),
                    (
                        "double_portrait",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "imageA",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label="Image"
                                                ),
                                            ),
                                            (
                                                "caption_text",
                                                wagtail.blocks.CharBlock(
                                                    label="Légende", required=False
                                                ),
                                            ),
                                            (
                                                "link",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "internal",
                                                            wagtail.blocks.PageChooserBlock(
                                                                label="Lien interne"
                                                            ),
                                                        ),
                                                        (
                                                            "external",
                                                            wagtail.blocks.URLBlock(
                                                                label="Lien externe"
                                                            ),
                                                        ),
                                                        (
                                                            "email",
                                                            wagtail.blocks.EmailBlock(
                                                                label="Email"
                                                            ),
                                                        ),
                                                    ],
                                                    label="Lien",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="Image de gauche",
                                    ),
                                ),
                                (
                                    "imageB",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    label="Image"
                                                ),
                                            ),
                                            (
                                                "caption_text",
                                                wagtail.blocks.CharBlock(
                                                    label="Légende", required=False
                                                ),
                                            ),
                                            (
                                                "link",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "internal",
                                                            wagtail.blocks.PageChooserBlock(
                                                                label="Lien interne"
                                                            ),
                                                        ),
                                                        (
                                                            "external",
                                                            wagtail.blocks.URLBlock(
                                                                label="Lien externe"
                                                            ),
                                                        ),
                                                        (
                                                            "email",
                                                            wagtail.blocks.EmailBlock(
                                                                label="Email"
                                                            ),
                                                        ),
                                                    ],
                                                    label="Lien",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="Image de droite",
                                    ),
                                ),
                            ],
                            group="Médias",
                            label="Bloc d'images format portrait",
                        ),
                    ),
                    (
                        "row_images",
                        wagtail.blocks.ListBlock(
                            core.blocks.ImageBlock,
                            group="Médias",
                            help_text="Il est possible d'ajouter 2 ou 3 images en lignes.",
                            label="Bloc d'images en ligne",
                            max=3,
                            min=2,
                        ),
                    ),
                    (
                        "cta_block",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.TextBlock(label="Titre")),
                                (
                                    "cta",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "cta_text",
                                                wagtail.blocks.CharBlock(
                                                    label="Texte du bouton"
                                                ),
                                            ),
                                            (
                                                "cta_link",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "internal",
                                                            wagtail.blocks.PageChooserBlock(
                                                                label="Lien interne"
                                                            ),
                                                        ),
                                                        (
                                                            "external",
                                                            wagtail.blocks.URLBlock(
                                                                label="Lien externe"
                                                            ),
                                                        ),
                                                        (
                                                            "email",
                                                            wagtail.blocks.EmailBlock(
                                                                label="Email"
                                                            ),
                                                        ),
                                                    ],
                                                    label="Lien du bouton",
                                                ),
                                            ),
                                        ],
                                        label="Bouton",
                                    ),
                                ),
                                (
                                    "with_background",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Si cette case est coché, le bloc est entouré d'un fond clair et le texte change de couleur.",
                                        label="Souhaitez-vous un fond clair ?",
                                    ),
                                ),
                            ],
                            label="Bloc d'appel à action",
                        ),
                    ),
                ],
                use_json_field=True,
                verbose_name="Corps de la page",
            ),
        ),
    ]
