# Generated by Django 4.2.18 on 2025-01-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0003_alter_journalpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalpage",
            name="intro",
            field=models.TextField(default={}, verbose_name="Introduction"),
            preserve_default=False,
        ),
    ]
