repos:
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.31.1 # grab latest tag from GitHub
    hooks:
      - id: djlint-django
  repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.2
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
  - repo: https://github.com/python/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: pre-commit-django-migrations
        name: Check django migrations
        entry: docker-compose exec -T wagtail python manage.py makemigrations --check --dry-run
        language: system
        types: [python]
        stages: [push]
        pass_filenames: false