version = 1
providers = ["python", "django"]

[phases.install]
commands = ["pip install -r requirements.txt"]


[start]
cmd = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn wwoof-demo.wsgi:application --bind 0.0.0.0:$PORT --workers 3"

[variables]
NIXPACKS_PYTHON_VERSION = "3.10"
NODE_VERSION = "18.x"
